// Theme definitions — clean minimalist, two complete visual systems
// neon: dark void with electric magenta/cyan
// summer: warm sunshine with ocean breeze

const themes = {
  neon: {
    id: 'neon',
    label: 'Neon',
    description: 'Dark synthwave — electric magenta on void',
    vars: {
      '--bg-primary': '#0a0a1a',
      '--bg-secondary': '#0f0f28',
      '--bg-card': '#151535',
      '--bg-hover': '#1c1c45',
      '--text-primary': '#f0e6ff',
      '--text-secondary': '#b8a0e0',
      '--text-muted': '#5a4a80',
      '--accent': '#e040fb',
      '--accent-glow': '#00e5ff',
      '--border': '#2a2050',
      '--border-hairline': '#1a1540',
      '--border-dashed': '#2a2050',
      '--font-display': "'Inter', 'SF Pro', system-ui, sans-serif",
      '--font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      '--font-body': "'Inter', system-ui, sans-serif",
      '--font-size-display': '48px',
      '--font-size-heading': '22px',
      '--font-size-body': '14px',
      '--font-size-caption': '10px',
      '--radius': '6px',
      '--shadow': '0 4px 24px rgba(224,64,251,0.15)',
      '--success': '#00e676',
      '--danger': '#ff1744',
      '--warning': '#ffd740',
      '--tag-official-bg': '#e040fb22',
      '--tag-official-text': '#e040fb',
      '--tag-community-bg': '#00e5ff22',
      '--tag-community-text': '#00e5ff',
      '--tag-builtin-bg': '#00e67622',
      '--tag-builtin-text': '#00e676',
    },
  },

  summer: {
    id: 'summer',
    label: 'Summer',
    description: 'Warm sunshine and ocean breeze — light & airy',
    vars: {
      '--bg-primary': '#fef9ef',
      '--bg-secondary': '#f5eed8',
      '--bg-card': '#fff8e8',
      '--bg-hover': '#fdf0d0',
      '--text-primary': '#2d1b00',
      '--text-secondary': '#6d4c00',
      '--text-muted': '#b8956e',
      '--accent': '#ff8f00',
      '--accent-glow': '#0097a7',
      '--border': '#e8d5b0',
      '--border-hairline': '#efe0c0',
      '--border-dashed': '#dcc8a0',
      '--font-display': "'Inter', 'SF Pro', system-ui, sans-serif",
      '--font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      '--font-body': "'Inter', system-ui, sans-serif",
      '--font-size-display': '48px',
      '--font-size-heading': '22px',
      '--font-size-body': '15px',
      '--font-size-caption': '10px',
      '--radius': '10px',
      '--shadow': '0 2px 16px rgba(0,0,0,0.08)',
      '--success': '#2e7d32',
      '--danger': '#c62828',
      '--warning': '#f57c00',
      '--tag-official-bg': '#ff8f0022',
      '--tag-official-text': '#e65100',
      '--tag-community-bg': '#0097a722',
      '--tag-community-text': '#006064',
      '--tag-builtin-bg': '#2e7d3222',
      '--tag-builtin-text': '#2e7d32',
    },
  },
};

export default themes;
