// Theme definitions — three complete visual systems mapped to CSS variables
// Index matches the user's numbering: theme 2, 3, 4

const themes = {
  dossier: {
    id: 'dossier',
    label: 'Classified Dossier',
    description: 'Cream paper, hairline rules, red dots, Anton + JetBrains Mono',
    vars: {
      '--bg-primary': '#faf7f0',
      '--bg-secondary': '#f0ece0',
      '--bg-card': '#f5f2e8',
      '--bg-hover': '#e8e4d4',
      '--text-primary': '#1a1a1a',
      '--text-secondary': '#555555',
      '--text-muted': '#888888',
      '--accent': '#cc1111',
      '--accent-glow': '#ff2222',
      '--border': '#1a1a1a',
      '--border-hairline': '#cccccc',
      '--border-dashed': '#aaaaaa',
      '--font-display': "'Anton', Impact, sans-serif",
      '--font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      '--font-body': "'Georgia', 'Times New Roman', serif",
      '--font-size-display': '120px',
      '--font-size-heading': '28px',
      '--font-size-body': '16px',
      '--font-size-caption': '10px',
      '--radius': '0px',
      '--shadow': 'none',
      '--success': '#2d6a2d',
      '--danger': '#cc1111',
      '--warning': '#886600',
      '--tag-official-bg': '#1a1a1a',
      '--tag-official-text': '#faf7f0',
      '--tag-community-bg': '#f0ece0',
      '--tag-community-text': '#555555',
      '--tag-builtin-bg': '#e8e4d4',
      '--tag-builtin-text': '#1a1a1a',
    },
  },

  industrial: {
    id: 'industrial',
    label: 'Dark Industrial',
    description: 'Steel grays, amber warnings, dense data panels',
    vars: {
      '--bg-primary': '#0d1117',
      '--bg-secondary': '#161b22',
      '--bg-card': '#1c2333',
      '--bg-hover': '#252d3a',
      '--text-primary': '#e6edf3',
      '--text-secondary': '#8b949e',
      '--text-muted': '#484f58',
      '--accent': '#f0883e',
      '--accent-glow': '#ff9d5c',
      '--border': '#30363d',
      '--border-hairline': '#21262d',
      '--border-dashed': '#30363d',
      '--font-display': "'Industry', 'Teko', 'Oswald', sans-serif",
      '--font-mono': "'Fira Code', 'JetBrains Mono', monospace",
      '--font-body': "'Inter', 'SF Pro', system-ui, sans-serif",
      '--font-size-display': '64px',
      '--font-size-heading': '20px',
      '--font-size-body': '14px',
      '--font-size-caption': '11px',
      '--radius': '4px',
      '--shadow': '0 4px 24px rgba(0,0,0,0.4)',
      '--success': '#3fb950',
      '--danger': '#f85149',
      '--warning': '#d29922',
      '--tag-official-bg': '#f0883e22',
      '--tag-official-text': '#f0883e',
      '--tag-community-bg': '#8b949e22',
      '--tag-community-text': '#8b949e',
      '--tag-builtin-bg': '#3fb95022',
      '--tag-builtin-text': '#3fb950',
    },
  },

  chaos: {
    id: 'chaos',
    label: 'Maximalist Chaos',
    description: 'Asymmetric layouts, neon blasts, 90s rave flyer energy',
    vars: {
      '--bg-primary': '#0a0a0a',
      '--bg-secondary': '#12001a',
      '--bg-card': '#1a0030',
      '--bg-hover': '#250045',
      '--text-primary': '#ffffff',
      '--text-secondary': '#cc88ff',
      '--text-muted': '#6633aa',
      '--accent': '#ff00ff',
      '--accent-glow': '#00ffff',
      '--border': '#ff00ff44',
      '--border-hairline': '#00ffff33',
      '--border-dashed': '#ff00ff22',
      '--font-display': "'Bebas Neue', 'Anton', 'Impact', sans-serif",
      '--font-mono': "'Fira Code', monospace",
      '--font-body': "'Inter', system-ui, sans-serif",
      '--font-size-display': '80px',
      '--font-size-heading': '26px',
      '--font-size-body': '15px',
      '--font-size-caption': '10px',
      '--radius': '0px 16px 0px 16px',
      '--shadow': '0 0 30px rgba(255,0,255,0.3), 0 0 60px rgba(0,255,255,0.1)',
      '--success': '#00ff88',
      '--danger': '#ff3366',
      '--warning': '#ffcc00',
      '--tag-official-bg': '#ff00ff33',
      '--tag-official-text': '#ff00ff',
      '--tag-community-bg': '#00ffff22',
      '--tag-community-text': '#00ffff',
      '--tag-builtin-bg': '#ffcc0022',
      '--tag-builtin-text': '#ffcc00',
    },
  },
};

export default themes;
